package Common.Enumerators;

import java.io.Serializable;

/**
 *  @author Amenta Stefano, Moroni Paolo 
 * Descrive tutte le possibili richieste che possono essere inoltrate dal client
 * al server
 *
 */
public enum RequestType implements Serializable {
	LOGIN_USER, CLOSE, GET_DEPARTMENTS, GET_DEGREE_COURSES, GET_COURSES, CREATE_USER, GET_FILE_SYSTEM,
	DOWNLOAD_DOCUMENT, CREATE_FOLDER, UPLOAD_DOCUMENT, PASSWORD_FORGET, CONFIRM_ACTIVATION_CODE, CREATE_COURSE, GET_ALL_TEACHERS, UPDATE_LOC, GET_SECONDS_AVERAGE, GET_LOGGED_USER_NUMBER, GET_LOGGED_NUMBER_BY_CORSO, 
	GET_NUMBER_ACCESS_BY_PERIOD, UPDATE_DOCUMENT_COUNT, DOCUMENT_COUNT_BY_CORSO, DOWNLOAD_USER_COUNT, GET_ALL_COURSES, SUBSCRIVE_COURSE,
	VERIFY_COD, GET_STUDENT_COURSES, GET_COURSE_DOCUMENTS, ACCOUNT_LOCK, MODIFY_COURSE, LINK_DOCENTE_CORSO, 
	PASSWORD_CHANGE, MODIFY_USER_DATA, GET_ALL_STUDENTS, GET_STUDENT_BY_USERID, GET_DEGREE_COURSES_BY_ID, CHANGE_FOLDER_VISIBILITY, //added
	UPDATE_DEGREE_COURSE, UPDATE_FOLDER_DESCRIPTION, IMPORT_CSV_FILE, GET_USER_TYPE, DELETE_USER, UNLOCK_USER, DELETE_COURSE,
	GET_LOCKED_TEACHERS, GET_LOCKED_STUDENTS, GET_LOCKED_ADMINS, INCREMENT_LOGIN_ATTEMPTS, GET_LOGIN_ATTEMPTS_NUMBER,
	SET_ZERO_LOGIN_ATTEMPTS, GET_DOCUMENTS, UPDATE_DOWNLOAD_COUNT, DELETE_FILE, DELETE_FOLDER, COURSE_DESCRIPTION, 
	GET_ALL_USERS, GET_STUDENTS_BY_COURSE, SEND_NEWSLETTER_TO_ALL_STUDENTS, SEND_NEWSLETTER_TO_SOME_USERS, 
	UPDATE_FILE_DESCRIPTION, GET_EMAIL_TEACHER_FROM_CORSO, GET_DOCTYPE_BY_DOCNAME, GET_ALL_ADMIN
}
